export const EQUIPOS_RPC_ERRORS: Record<string, string> = {
  no_auth: "Tenés que iniciar sesión.",
  nombre_requerido: "El nombre del equipo es obligatorio.",
  no_capitan: "Solo el capitán puede hacer esto.",
  enlace_invalido: "El enlace no existe o ya no está activo.",
  ya_es_miembro: "Ya formás parte de este equipo.",
  ya_pendiente: "Ya hay una solicitud o invitación pendiente.",
  identificador_requerido: "Ingresá un username o teléfono.",
  usuario_no_encontrado: "No encontramos a nadie con ese username o teléfono.",
  no_auto_invitar: "No podés invitarte a vos mismo.",
  no_existe: "No encontramos esa solicitud.",
  no_pendiente: "Esa solicitud ya no está pendiente.",
  no_destinatario: "Esta invitación no es para tu cuenta.",
  capitan_debe_transferir: "El capitán no puede salir sin transferir la capitanía.",
  no_miembro: "No sos miembro de este equipo.",
  mismo_usuario: "Elegí otro jugador para la capitanía.",
  destino_no_miembro: "Ese usuario no es miembro activo del equipo.",
  no_auto_expulsar: "No podés expulsarte a vos mismo.",
  desafio_no_existe: "No encontramos ese desafío.",
  desafio_cerrado: "Ese desafío ya no está abierto.",
  inscripcion_cerrada: "Se cerró el tiempo para inscribir.",
  convocados_requeridos: "Marcá quiénes juegan.",
  minimo_convocados: "No llega al mínimo de convocados para ese formato.",
  convocado_no_miembro: "Hay alguien marcado que no está en el plantel.",
  convocado_ocupado: "Alguien de la lista ya está convocado en el otro equipo.",
  falta_nacimiento: "Falta la fecha de nacimiento en el perfil.",
  falta_dni: "Para desafíos por la cancha necesitás cargar tu DNI.",
  dni_invalido: "Ingresá un DNI válido (7 u 8 números).",
  fecha_nacimiento_invalida: "La fecha de nacimiento no es válida.",
  menor_13: "Tenés que tener al menos 13 años.",
  menor_18: "Esta acción es solo para mayores de 18.",
  regla_empate_invalida: "Elegí qué pasa si empatan: penales o mitad de cancha para cada uno.",
  tarifa_no_configurada: "Falta configurar la tarifa de servicio.",
  turno_no_existe: "No encontramos ese turno.",
  turno_no_disponible: "Ese turno ya no está disponible.",
  turno_pasado: "Ese turno ya pasó.",
  precio_cancha_invalido: "Ese turno no tiene precio de cancha.",
  campo_no_existe: "No encontramos la cancha de ese turno.",
  no_es_por_la_cancha: "Ese partido no es por la cancha.",
  no_listo_para_liquidar: "Este partido todavía no se puede liquidar.",
  no_listo_para_resultado: "Todavía no se puede confirmar el resultado.",
  partido_no_empezo: "El partido todavía no empezó.",
  empate_no_permitido: "En este partido el empate se define por penales.",
  ganador_invalido: "Elegí uno de los dos equipos.",
  ya_cerrado: "El otro capitán ya confirmó: ya no se puede corregir.",
  no_admin: "Solo un administrador puede resolver la disputa.",
  no_esta_en_disputa: "Ese partido no está en disputa.",
  reserva_vencida: "Se venció la reserva de 15 minutos.",
  pago_fuera_de_tiempo: "El pago llegó tarde o el cupo ya no está.",
  faltan_equipos: "Faltan los dos equipos pagos para liquidar.",
  resultado_incompleto: "Falta confirmar el resultado.",
  no_pendiente_pago: "Esa inscripción no está esperando pago.",
  ya_inscripto: "Ese equipo ya está inscripto.",
  bloqueado: "No se puede invitar: hay un bloqueo entre estas cuentas.",
  ya_reportado: "Ya denunciaste a esta persona. La estamos revisando.",
  motivo_invalido: "Elegí un motivo para la denuncia.",
  usuario_requerido: "Falta el usuario.",
  no_auto: "Eso no aplica a tu propia cuenta.",
  cupo_lleno: "Ya no hay lugar en este desafío.",
  no_activa: "Esa inscripción ya no está activa.",
  fuera_de_plazo: "Ya no se puede cancelar: pasó el plazo.",
  desafios_no_habilitados: "Este predio no admite desafíos en esa cancha.",
  horario_no_habilitado: "Ese horario no está habilitado para desafíos.",
  anticipacion_insuficiente: "Hay que publicar con más anticipación para ese formato.",
  sena_supera_maximo: "La seña no puede pasar el máximo de la plataforma (50% de la cancha).",
  cierre_sin_rival_bajo: "El cierre sin rival no puede ser de menos de 3 horas.",
  anticipacion_minima_baja: "La anticipación mínima no puede ser de menos de 3 horas.",
  politica_invalida: "Revisá los datos de la política.",
  premios_deshabilitados: "Los premios siguen deshabilitados.",
  no_dueno_predio: "Solo el dueño del predio puede hacer eso.",
  no_periodo_gratis: "Ya no se puede cancelar gratis: pasaron las 24 horas o el partido se publicó con menos de 48 horas.",
  decision_invalida: "Esa opción no está disponible ahora.",
  requiere_confirmar_riesgo: "Tenés que confirmar que, si nadie se suma, se cobra la cancha completa.",
  no_permitido_seguir_inicio: "Este predio no deja seguir buscando hasta el inicio.",
  hay_rival: "Ya hay un rival: el partido está confirmado.",
  no_es_equipo_a: "Solo el equipo que publicó puede decidir esto.",
  todavia_no_cierre: "Todavía no llegó el cierre de búsqueda.",
  sena_invalida: "No se pudo calcular el cargo sin rival.",
  no_completo: "Este partido todavía no está confirmado con los dos equipos.",
  tolerancia_no_cumplida: "Todavía no pasó el tiempo de espera para informar que el rival no está.",
  reprogramar_no_pedido: "Este partido no está esperando un nuevo turno.",
  turno_distinto_campo: "El nuevo turno tiene que ser de la misma cancha.",
  usar_decidir_sin_rival: "Todavía no hay rival: usá las opciones de búsqueda.",
  hay_sueltos: "Ya hay jugadores sueltos anotados. No se puede sumar un equipo rival.",
  hay_equipo_rival: "Ya hay un equipo rival. No se puede entrar suelto.",
  no_es_amistoso: "Eso solo aplica a un amistoso.",
  walkover_solo_equipo: "La inasistencia se informa cuando el rival es un equipo.",
  checkout_prueba_off: "El cobro de prueba no está activo.",
  tipo_cobro_invalido: "Elegí seña o pago total.",
  reglas_no_aceptadas: "Tenés que aceptar las reglas del predio para reservar.",
  monto_invalido: "El monto del pago no coincide con la cotización.",
  titular_nombre_requerido: "Ingresá el nombre de quien reserva.",
  telefono_invalido: "Ingresá un teléfono válido.",
  ya_reclamada: "Esa reserva ya está asociada a otra cuenta.",
  codigo_invalido: "Ese código no es válido.",
  codigo_vencido: "Se venció el código. Pedí uno nuevo.",
  demasiados_intentos: "Demasiados intentos. Esperá un rato y pedí otro código.",
  sms_espera: "Esperá un minuto para pedir otro código.",
  usar_sms_api: "El envío de SMS no está configurado.",
  horario_ya_reservado: "Este horario ya fue reservado.",
  enlace_vencido: "Ese enlace ya no vale: el horario ya pasó.",
  cobro_externo_invalido: "Elegí si la seña ya se cobró afuera o si se cobra en el predio.",
  senia_no_configurada: "Falta el monto de la seña.",
};

export function mensajeErrorEquipo(code: string | null | undefined, extra?: { quienes?: string; minimo?: number }): string {
  if (!code) return "No se pudo completar la acción.";
  if (code === "falta_nacimiento" && extra?.quienes) {
    return `Les falta la fecha de nacimiento: ${extra.quienes}.`;
  }
  if (code === "menor_18" && extra?.quienes) {
    return `Menores de 18: ${extra.quienes}. Para por la cancha tienen que ser mayores de 18.`;
  }
  if (code === "menor_13" && extra?.quienes) {
    return `Menores de 13: ${extra.quienes}. Tienen que tener al menos 13 años.`;
  }
  if (code === "minimo_convocados" && extra?.minimo) {
    return `Tenés que convocar al menos ${extra.minimo} jugadores para este formato.`;
  }
  return EQUIPOS_RPC_ERRORS[code] ?? code;
}
